spring:
  application:
    name: beatstore
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

garage:
  endpoint: ${GARAGE_ENDPOINT}
  access-key: ${GARAGE_ACCESS_KEY}
  secret-key: ${GARAGE_SECRET_KEY}
  region: ${GARAGE_REGION}
  bucket: ${GARAGE_BUCKET}
